# Gunakan image node:22-alpine sebagai base image

# Tetapkan direktori ke /app (tempat semua perintah selanjutnya dijalankan)

# Salin file package.json dan package-lock.json ke dalam image

# Install dependensi yang tercantum di package.json

# Salin seluruh proyek ke dalam image (termasuk source code)

# Buka port 5173 (port default Vite), yang digunakan image untuk menrima koneksi

# Jalankan perintah npm run dev untuk memulai server pengembangan Vite (kalo mau konfigurasi pake nginx bole aja)